### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by 11mLLM** [11mLLM/Prompt-Engineering-Guide#22]
[1차 리뷰 결과물](https://github.com/11mLLM/11mLLM/issues/1) << Click !

## ☑️ Checklist

1. 의미 왜곡이 없으며 원문의 핵심을 포착했는가?
2. 맞춤법과 문법을 준수하는가?
3. 일관성있는 어조인가?
4. 문맥적 오류가 있는가?
5. 합의한 용어를 준수하는가?

**Comment by 11mLLM** [comment]
@temtomk

**Comment by temtomk** [comment]
test

**Comment by temtomk** [comment]
test

**Comment by Hr0803** [comment]
Assignee에 등록이 안되어 있습니다!

**Comment by Esantomi** [comment]
2차 리뷰 현황
- [X] [Update pages/introduction/*.kr.mdx #2](https://github.com/11mLLM/Prompt-Engineering-Guide/pull/2)
- [X] [docs: index.kr.mdx and tips.kr.mdx #9](https://github.com/11mLLM/Prompt-Engineering-Guide/pull/9)
- [ ] [[intro] docs: modify basics.kr.mdx, elements.kr.mdx, _meta.kr.json #1](https://github.com/11mLLM/Prompt-Engineering-Guide/pull/1)

**Comment by Hr0803** [comment]
2차리뷰 모두 완료하였습니다.

- [x] Update pages/introduction/*.kr.mdx #2
- [x] docs: index.kr.mdx and tips.kr.mdx #9
- [x] docs: modify basics.kr.mdx, elements.kr.mdx, _meta.kr.json #1

**Comment by 11mLLM** [comment]
리뷰 2차 완료 ✅
